# Generated by Django 4.1.7 on 2023-04-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genq_kyc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kyc_Details',
            new_name='Kyc_Detail',
        ),
    ]
