# Generated by Django 4.1.7 on 2023-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genq_kyc_app', '0003_alter_kyc_detail_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_detail',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_detail',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_detail',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='kyc_detail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_detail',
            name='phone_num1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_detail',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_detail',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
