# Generated by Django 4.1.7 on 2023-04-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genq_kyc_app', '0004_alter_kyc_detail_country_alter_kyc_detail_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc_detail',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
