# Generated by Django 4.1.7 on 2023-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genq_kyc_app', '0005_rename_dob_kyc_detail_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_detail',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=10, null=True),
        ),
    ]
